project:
  type: book
  resources:
    - datasets
    - project-1/intro/index_files/

book:
  title: "Probability and Statistics Exercises"
  author: "Sera Gunn"
  date: today
  repo-url: https://github.com/seragunn/probstats-exercises/
  site-url: https://seragunn.github.io/probstats-exercises/
  repo-actions: [edit, issue, source]
  sidebar:
    background: primary
  navbar:
    background: "#222"
    left:
      - text: Home
        href: https://seragunn.github.io/
  chapters:
    - index.qmd
    - part: "Introduction to Data"
      chapters:
        - project-1/slides.qmd
        - project-1/intro.qmd
        - project-1/bars-and-pies.qmd
    - part: "Summarizing Data"
      chapters:
        - project-2/calculating-statistics.qmd
        - project-2/box-hist.qmd
        - project-2/visualizing-shape.qmd
    - part: "Introduction to Sampling"
      chapters:
        - project-3/intro-to-sampling.qmd
    - part: "The Binomial Distrubution"
      chapters:
        - project-4/distributions.qmd
        - project-4/binomial.qmd
    - part: "The Normal Distribution"
      chapters:
        - project-5/normal.qmd
    - part: "Confidence Intervals"
      chapters:
        - project-6/ci.qmd
    - part: "Hypothesis Testing"
      chapters:
        - project-7/hyptest.qmd

format:
  live-html:
    theme: [journal, theme.scss]
    css: style.css
